export const MIN_INPUT_SIZE = {
  WIDTH: 2,
  HEIGHT: 2
};

export const MIN_INPUT_OPACITY = 0.2;

export const INPUT_TYPE_NONE = 'NONE';

export const CONTEXT_MENU_IDS = {
  LABLE_USERNAME: 'LABEL_USERNAME',
  LABEL_USERNAME_YES: 'LABEL_USERNAME_YES',
  LABEL_USERNAME_NO: 'LABEL_USERNAME_NO'
}
